version: '3.6'

services:

  #prodigy:
  #  build: 
  #    context: prodigy
  #    dockerfile: ./Dockerfile
  #    args:
  #      PRODIGY_WHEEL: ${PRODIGY_WHEEL}
  #      SPACY_MODEL_URL: ${SPACY_MODEL_URL}
  #  image: "989477750762.dkr.ecr.eu-west-1.amazonaws.com/mantisnlp-prodigy:${VERSION}"
  #  entrypoint: python3 -m prodigy
  #  volumes:
  #    - "${PRODIGY_DATA}:/prodigy/data"
  #    - "${PRODIGY_MODELS}:/prodigy/models"
  #    - "${PRODIGY_RECIPES}:/prodigy/recipes"
  #    - "${PRODIGY_HOME}/prodigy.json:/prodigy/prodigy.json:ro"
  #  ports:
  #    - 8080:8080

  db:
    image: postgres:12.7-buster
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prodigy
      POSTGRES_USER: prodigy
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
